"""program repos

Revision ID: 03c11e20fdff
Revises: 2ae13d68f0e8
Create Date: 2026-08-10 11:18:42.498269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c11e20fdff'
down_revision: Union[str, Sequence[str], None] = '2ae13d68f0e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_repos', sa.Column('readiness_source', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_repos', 'readiness_source')
    # ### end Alembic commands ###
