"""programme tables

Revision ID: 2ae13d68f0e8
Revises: cc5feda8fe3d
Create Date: 2026-08-09 09:49:54.072949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae13d68f0e8'
down_revision: Union[str, Sequence[str], None] = 'cc5feda8fe3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pat', sa.Text(), nullable=False),
    sa.Column('bearer_token', sa.String(length=255), nullable=False),
    sa.Column('workspace_root', sa.Text(), nullable=False),
    sa.Column('board_project_owner', sa.String(length=255), nullable=True),
    sa.Column('board_project_number', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_bearer_token'), 'tenants', ['bearer_token'], unique=True)
    op.create_table('tenant_programme_connections',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('ref', sa.String(length=512), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_tenant_programme_connections_tenant_id')
    )
    op.create_index(op.f('ix_tenant_programme_connections_tenant_id'), 'tenant_programme_connections', ['tenant_id'], unique=False)
    op.create_table('tenant_repos',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('harness_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'org', 'repo', name='uq_tenant_repos_tenant_org_repo')
    )
    op.create_index(op.f('ix_tenant_repos_tenant_id'), 'tenant_repos', ['tenant_id'], unique=False)
    op.create_table('tenant_users',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('identity', sa.String(length=512), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'identity', name='uq_tenant_users_tenant_identity')
    )
    op.create_index(op.f('ix_tenant_users_tenant_id'), 'tenant_users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_users_tenant_id'), table_name='tenant_users')
    op.drop_table('tenant_users')
    op.drop_index(op.f('ix_tenant_repos_tenant_id'), table_name='tenant_repos')
    op.drop_table('tenant_repos')
    op.drop_index(op.f('ix_tenant_programme_connections_tenant_id'), table_name='tenant_programme_connections')
    op.drop_table('tenant_programme_connections')
    op.drop_index(op.f('ix_tenants_bearer_token'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
