"""onboarded programme meta prs

Revision ID: 48b0d306403c
Revises: 58462eaba680
Create Date: 2026-08-17 15:20:42.218517

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48b0d306403c"
down_revision: Union[str, Sequence[str], None] = "58462eaba680"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "programme_meta_prs",
        sa.Column("programme_id", sa.UUID(), nullable=False),
        sa.Column("html_url", sa.Text(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("initiative_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False, comment="Unique identifier for the record"),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment="Timestamp (UTC) when record was created",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="Timestamp (UTC) when record was last updated",
        ),
        sa.ForeignKeyConstraint(["programme_id"], ["programmes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("programme_id", "html_url", name="uq_programme_meta_prs_programme_url"),
        sa.UniqueConstraint(
            "programme_id", "number", name="uq_programme_meta_prs_programme_number"
        ),
    )
    op.create_index(
        op.f("ix_programme_meta_prs_programme_id"),
        "programme_meta_prs",
        ["programme_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_programme_meta_prs_programme_id"), table_name="programme_meta_prs")
    op.drop_table("programme_meta_prs")
    # ### end Alembic commands ###
