"""add_user_identities

Revision ID: 5c8536ec7078
Revises: 03c11e20fdff
Create Date: 2026-08-11 08:26:54.287225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8536ec7078'
down_revision: Union[str, Sequence[str], None] = '03c11e20fdff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_identities',
    sa.Column('credential_identifier', sa.String(length=512), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_identifier', name='uq_user_identities_credential_identifier')
    )
    op.create_index(op.f('ix_user_identities_credential_identifier'), 'user_identities', ['credential_identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_identities_credential_identifier'), table_name='user_identities')
    op.drop_table('user_identities')
    # ### end Alembic commands ###
