"""first version

Revision ID: 5e85268f844f
Revises: 
Create Date: 2026-08-11 11:33:17.601781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e85268f844f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_agent_catalogue',
    sa.Column('runner_id', sa.String(length=128), nullable=False),
    sa.Column('credential', sa.Text(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('runner_id', name='uq_platform_agent_catalogue_runner_id')
    )
    op.create_index(op.f('ix_platform_agent_catalogue_runner_id'), 'platform_agent_catalogue', ['runner_id'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pat', sa.Text(), nullable=False),
    sa.Column('bearer_token', sa.String(length=255), nullable=False),
    sa.Column('workspace_root', sa.Text(), nullable=False),
    sa.Column('board_project_owner', sa.String(length=255), nullable=True),
    sa.Column('board_project_number', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_bearer_token'), 'tenants', ['bearer_token'], unique=True)
    op.create_table('user_identities',
    sa.Column('credential_identifier', sa.String(length=512), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_identifier', name='uq_user_identities_credential_identifier')
    )
    op.create_index(op.f('ix_user_identities_credential_identifier'), 'user_identities', ['credential_identifier'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('delivery_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_delivery_id'), 'webhook_deliveries', ['delivery_id'], unique=True)
    op.create_table('jobs',
    sa.Column('status_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delivery_id', sa.String(length=255), nullable=False),
    sa.Column('webhook_delivery_id', sa.UUID(), nullable=True),
    sa.Column('claimed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('processed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.ForeignKeyConstraint(['webhook_delivery_id'], ['webhook_deliveries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_delivery_id'), 'jobs', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_jobs_status_type'), 'jobs', ['status_type'], unique=False)
    op.create_table('programmes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('github_pat', sa.Text(), nullable=False),
    sa.Column('workspace_root', sa.Text(), nullable=False),
    sa.Column('meta_org', sa.String(length=255), nullable=False),
    sa.Column('meta_repo', sa.String(length=255), nullable=False),
    sa.Column('meta_ref', sa.String(length=512), nullable=True),
    sa.Column('github_app_id', sa.String(length=255), nullable=True),
    sa.Column('github_installation_id', sa.String(length=255), nullable=True),
    sa.Column('lane_defaults', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programmes_tenant_id'), 'programmes', ['tenant_id'], unique=True)
    op.create_table('runs',
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('status_type', sa.String(length=64), nullable=False),
    sa.Column('outcome_type', sa.String(length=64), nullable=True),
    sa.Column('workflow_node', sa.String(length=255), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('issue_number', sa.Integer(), nullable=True),
    sa.Column('initiative_id', sa.String(length=255), nullable=True),
    sa.Column('wave_id', sa.String(length=64), nullable=True),
    sa.Column('wave_duration_ms', sa.Integer(), nullable=True),
    sa.Column('handoff_path', sa.Text(), nullable=True),
    sa.Column('meta_pr_url', sa.Text(), nullable=True),
    sa.Column('meta_head_sha', sa.String(length=64), nullable=True),
    sa.Column('retry_counter', sa.Integer(), nullable=False),
    sa.Column('notify_pending', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_tenant_id'), 'runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_runs_wave_id'), 'runs', ['wave_id'], unique=False)
    op.create_table('tenant_programme_connections',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('ref', sa.String(length=512), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_tenant_programme_connections_tenant_id')
    )
    op.create_index(op.f('ix_tenant_programme_connections_tenant_id'), 'tenant_programme_connections', ['tenant_id'], unique=False)
    op.create_table('tenant_repos',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('harness_verified', sa.Boolean(), nullable=False),
    sa.Column('readiness_source', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'org', 'repo', name='uq_tenant_repos_tenant_org_repo')
    )
    op.create_index(op.f('ix_tenant_repos_tenant_id'), 'tenant_repos', ['tenant_id'], unique=False)
    op.create_table('tenant_users',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('identity', sa.String(length=512), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'identity', name='uq_tenant_users_tenant_identity')
    )
    op.create_index(op.f('ix_tenant_users_tenant_id'), 'tenant_users', ['tenant_id'], unique=False)
    op.create_table('learning_extracts',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('initiative_id', sa.String(length=255), nullable=False),
    sa.Column('wave_id', sa.String(length=64), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('human_fix_detected', sa.Boolean(), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=False),
    sa.Column('source_sha', sa.String(length=64), nullable=True),
    sa.Column('prior_run_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_extracts_initiative_id'), 'learning_extracts', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_learning_extracts_run_id'), 'learning_extracts', ['run_id'], unique=True)
    op.create_index(op.f('ix_learning_extracts_wave_id'), 'learning_extracts', ['wave_id'], unique=False)
    op.create_table('run_events',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('workflow_node', sa.String(length=255), nullable=True),
    sa.Column('outcome_type', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_events_run_id'), 'run_events', ['run_id'], unique=False)
    op.create_table('stages',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('workflow_node', sa.String(length=255), nullable=False),
    sa.Column('outcome_type', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('runner', sa.String(length=128), nullable=True),
    sa.Column('model_profile', sa.String(length=128), nullable=True),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('model_provider', sa.String(length=128), nullable=True),
    sa.Column('prompt_id', sa.String(length=255), nullable=True),
    sa.Column('prompt_revision', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stages_run_id'), 'stages', ['run_id'], unique=False)
    op.create_table('learning_items',
    sa.Column('extract_id', sa.UUID(), nullable=False),
    sa.Column('item_key', sa.String(length=64), nullable=False),
    sa.Column('class_type', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('codify_hint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status_type', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.ForeignKeyConstraint(['extract_id'], ['learning_extracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extract_id', 'item_key', name='uq_learning_items_extract_key')
    )
    op.create_index(op.f('ix_learning_items_extract_id'), 'learning_items', ['extract_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_items_extract_id'), table_name='learning_items')
    op.drop_table('learning_items')
    op.drop_index(op.f('ix_stages_run_id'), table_name='stages')
    op.drop_table('stages')
    op.drop_index(op.f('ix_run_events_run_id'), table_name='run_events')
    op.drop_table('run_events')
    op.drop_index(op.f('ix_learning_extracts_wave_id'), table_name='learning_extracts')
    op.drop_index(op.f('ix_learning_extracts_run_id'), table_name='learning_extracts')
    op.drop_index(op.f('ix_learning_extracts_initiative_id'), table_name='learning_extracts')
    op.drop_table('learning_extracts')
    op.drop_index(op.f('ix_tenant_users_tenant_id'), table_name='tenant_users')
    op.drop_table('tenant_users')
    op.drop_index(op.f('ix_tenant_repos_tenant_id'), table_name='tenant_repos')
    op.drop_table('tenant_repos')
    op.drop_index(op.f('ix_tenant_programme_connections_tenant_id'), table_name='tenant_programme_connections')
    op.drop_table('tenant_programme_connections')
    op.drop_index(op.f('ix_runs_wave_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_tenant_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_programmes_tenant_id'), table_name='programmes')
    op.drop_table('programmes')
    op.drop_index(op.f('ix_jobs_status_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_delivery_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_webhook_deliveries_delivery_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_user_identities_credential_identifier'), table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_index(op.f('ix_tenants_bearer_token'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_platform_agent_catalogue_runner_id'), table_name='platform_agent_catalogue')
    op.drop_table('platform_agent_catalogue')
    # ### end Alembic commands ###
