"""first version

<<<<<<<< HEAD:postgres_migrations/versions/a50807500528_first_version.py
Revision ID: a50807500528
Revises: 
Create Date: 2026-07-28 06:00:04.616578
========
Revision ID: 69de74666068
Revises: 
Create Date: 2026-07-28 05:53:29.269428
>>>>>>>> 496efc9 ([INIT-GATEFLOW-005 W0] Squash Postgres migrations into a single baseline.):postgres_migrations/versions/69de74666068_first_version.py

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
<<<<<<<< HEAD:postgres_migrations/versions/a50807500528_first_version.py
revision: str = 'a50807500528'
========
revision: str = '69de74666068'
>>>>>>>> 496efc9 ([INIT-GATEFLOW-005 W0] Squash Postgres migrations into a single baseline.):postgres_migrations/versions/69de74666068_first_version.py
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('status_type', sa.String(length=64), nullable=False),
    sa.Column('outcome_type', sa.String(length=64), nullable=True),
    sa.Column('workflow_node', sa.String(length=255), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('issue_number', sa.Integer(), nullable=True),
    sa.Column('initiative_id', sa.String(length=255), nullable=True),
    sa.Column('wave_id', sa.String(length=64), nullable=True),
    sa.Column('wave_duration_ms', sa.Integer(), nullable=True),
<<<<<<<< HEAD:postgres_migrations/versions/a50807500528_first_version.py
========
    sa.Column('handoff_path', sa.Text(), nullable=True),
>>>>>>>> 496efc9 ([INIT-GATEFLOW-005 W0] Squash Postgres migrations into a single baseline.):postgres_migrations/versions/69de74666068_first_version.py
    sa.Column('retry_counter', sa.Integer(), nullable=False),
    sa.Column('notify_pending', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_wave_id'), 'runs', ['wave_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('delivery_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_delivery_id'), 'webhook_deliveries', ['delivery_id'], unique=True)
    op.create_table('jobs',
    sa.Column('status_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delivery_id', sa.String(length=255), nullable=False),
    sa.Column('webhook_delivery_id', sa.UUID(), nullable=True),
    sa.Column('claimed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('processed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.ForeignKeyConstraint(['webhook_delivery_id'], ['webhook_deliveries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_delivery_id'), 'jobs', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_jobs_status_type'), 'jobs', ['status_type'], unique=False)
    op.create_table('run_events',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('workflow_node', sa.String(length=255), nullable=True),
    sa.Column('outcome_type', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_events_run_id'), 'run_events', ['run_id'], unique=False)
    op.create_table('stages',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('workflow_node', sa.String(length=255), nullable=False),
    sa.Column('outcome_type', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('runner', sa.String(length=128), nullable=True),
    sa.Column('model_profile', sa.String(length=128), nullable=True),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('model_provider', sa.String(length=128), nullable=True),
    sa.Column('prompt_id', sa.String(length=255), nullable=True),
    sa.Column('prompt_revision', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stages_run_id'), 'stages', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stages_run_id'), table_name='stages')
    op.drop_table('stages')
    op.drop_index(op.f('ix_run_events_run_id'), table_name='run_events')
    op.drop_table('run_events')
    op.drop_index(op.f('ix_jobs_status_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_delivery_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_webhook_deliveries_delivery_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_runs_wave_id'), table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
