"""add_runs_wave_duration_ms

Revision ID: 7e79269bd50b
Revises: bc8abad9a701
Create Date: 2026-07-24 23:13:27.166009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e79269bd50b'
down_revision: Union[str, Sequence[str], None] = 'bc8abad9a701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('wave_duration_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'wave_duration_ms')
    # ### end Alembic commands ###
