"""add_runs_wave_id

Revision ID: bc8abad9a701
Revises: 36b36d3d4fc9
Create Date: 2026-07-24 14:05:24.972935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8abad9a701'
down_revision: Union[str, Sequence[str], None] = '36b36d3d4fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('wave_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_runs_wave_id'), 'runs', ['wave_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_wave_id'), table_name='runs')
    op.drop_column('runs', 'wave_id')
    # ### end Alembic commands ###
