"""add learning extracts and items

Revision ID: cc5feda8fe3d
Revises: 1cd9a83a94a2
Create Date: 2026-08-01 06:35:20.142434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc5feda8fe3d'
down_revision: Union[str, Sequence[str], None] = '1cd9a83a94a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_extracts',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('initiative_id', sa.String(length=255), nullable=False),
    sa.Column('wave_id', sa.String(length=64), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('human_fix_detected', sa.Boolean(), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=False),
    sa.Column('source_sha', sa.String(length=64), nullable=True),
    sa.Column('prior_run_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_extracts_initiative_id'), 'learning_extracts', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_learning_extracts_run_id'), 'learning_extracts', ['run_id'], unique=True)
    op.create_index(op.f('ix_learning_extracts_wave_id'), 'learning_extracts', ['wave_id'], unique=False)
    op.create_table('learning_items',
    sa.Column('extract_id', sa.UUID(), nullable=False),
    sa.Column('item_key', sa.String(length=64), nullable=False),
    sa.Column('class_type', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('codify_hint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status_type', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp (UTC) when record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp (UTC) when record was last updated'),
    sa.ForeignKeyConstraint(['extract_id'], ['learning_extracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extract_id', 'item_key', name='uq_learning_items_extract_key')
    )
    op.create_index(op.f('ix_learning_items_extract_id'), 'learning_items', ['extract_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_items_extract_id'), table_name='learning_items')
    op.drop_table('learning_items')
    op.drop_index(op.f('ix_learning_extracts_wave_id'), table_name='learning_extracts')
    op.drop_index(op.f('ix_learning_extracts_run_id'), table_name='learning_extracts')
    op.drop_index(op.f('ix_learning_extracts_initiative_id'), table_name='learning_extracts')
    op.drop_table('learning_extracts')
    # ### end Alembic commands ###
