"""run schema update

Revision ID: e7263d04aa6b
Revises: 7e79269bd50b
Create Date: 2026-07-28 05:10:28.330091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7263d04aa6b'
down_revision: Union[str, Sequence[str], None] = '7e79269bd50b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('handoff_path', sa.Text(), nullable=True))
    op.add_column('stages', sa.Column('prompt_id', sa.String(length=255), nullable=True))
    op.add_column('stages', sa.Column('prompt_revision', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stages', 'prompt_revision')
    op.drop_column('stages', 'prompt_id')
    op.drop_column('runs', 'handoff_path')
    # ### end Alembic commands ###
